pulp-platform/ara

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- README.md
With this PR, we only run the CI upon a push. We also add a badge of the `ci` workflow on the README.
> Improve the GitHub CI 

- .github/pull_request_template.md
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- CHANGELOG.md
- CODEOWNERS
- CONTRIBUTING.md
- DEPENDENCIES.md
- apps/common/riscv_test.h
- apps/common/runtime.h
- apps/fmatmul/kernel/matmul.c
- apps/fmatmul/kernel/matmul.h
- apps/fmatmul/main.c
- apps/imatmul/kernel/matmul.c
- apps/imatmul/kernel/matmul.h
- apps/imatmul/main.c
- scripts/run-clang-format.py
This MR updates the contribution guidelines, and improves the linting CI workflow. The applications in the `apps` folder are now checked against `clang-format`. The CI workflow also checks for trailing whitespace and tabs.
> Improve the linting workflow

- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_soc.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/operand_queue.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/lane/vector_fus_stage.sv
- hardware/src/lane/vmfpu.sv
With this PR, I move the RVVD, RVVF, and RVVH parameters from `ara_pkg` to a parameter of `ara_soc`, which is propagated all the way down to the FPU.
- FPUSupport parameter to ara_soc, determining which floating-point representations are supported by Ara.
> Add FPU Support as an ara_soc parameter

- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_soc.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/operand_queue.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/lane/vector_fus_stage.sv
- hardware/src/lane/vmfpu.sv
Add four new parameters to tune the support for floating-point operations in general, or just for specific formats. 
* `RVV_FP`: enables/disables the decoding of `OPFVV` and `OPFVF` instructions, the FPU, the FP re-encodings in `vmfpu` and `operand_queue`.
* `RVVH`: enable/disable support for 16b floating-point operations. This can be enabled only if CVA6 supports these operations as well (`ariane_pkg::XF16` == `1'b1`).
* `RVVF`: enable/disable support for 32b floating-point operations.
* `RVVD`: enable/disable support for 64b floating-point operations.
- Parametrization for FPU and FPU-specific formats support
> Add parametrization for FPU and FPU-specific formats support

- CHANGELOG.md
- Makefile
Description of PR that completes issue here...
- Removed dependency in Makefile to use a specific gcc version
- Used only `gcc` and `g++` commands so that the correct version is picked up by the build system
- Used only `gcc` and `g++` commands so that the correct version is picked up by the build system
> Removing dependency for a specific gcc version

- CHANGELOG.md
- apps/common/encoding.h
This PR copies `encoding.h` from the Spike submodule to the common Ara runtime.
Closes #32.
- The `encoding.h` in the common Ara runtime is now a copy from the `encoding.h` in the Spike submodule
> Copy encoding.h from Spike to the common Ara runtime

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- hardware/Makefile
I found out that it is much faster to compile the Verilated model of Ara with `clang` than with `gcc`. The runtime of the latest CI run brought the compilation time from 1h40min to about 10min, a fraction of the time. 
This PR compiles Verilator with `clang`, so that it uses LLVM when compiling the model. It also updates the CI to install LLVM before running the compilation.
- Compile Verilator and Ara's verilated model with LLVM, for a faster compile time.
> Verilation with LLVM

- CHANGELOG.md
- README.md
Description of PR that completes issue here...
- The README instruction to build llvm toolchain will result in error. I fixed the README to use the correct target in the Makefile.
- The README instruction to compile hardware will result in error. The correct target to call is to use `make compile` and not `make build`
> [README] Fix for typos in build instructions

- CHANGELOG.md
- apps/fmatmul/kernel/fmatmul.c
- apps/fmatmul/kernel/fmatmul.h
- apps/imatmul/kernel/imatmul.c
- apps/imatmul/kernel/imatmul.h
- hardware/src/ara_soc.sv
This PR improves the performance of Ara on the matrix multiplication kernels. It does so by widening Ariane's cache lines to 256 bits (I$) and 512 bits (D$), and by issuing vector instructions back-to-back. 
Merge this after merging #54.
I still need to check the performance impacts of those changes on the interface between Ara and Ariane. 
- Widen CVA6's cache lines
- Implement back-to-back accelerator instruction issue mechanism on CVA6
> Performance improvements

- .github/workflows/ci.yml
- CHANGELOG.md
This PR fixes the installation of `gnuplot` on GitHub's CI by running `apt-get update` before installing the package.
- Fix Gnuplot installation on GitHub's CI
> Fix Gnuplot

- .gitmodules
- CHANGELOG.md
- Makefile
Addressing issues https://github.com/pulp-platform/ara/issues/64 and https://github.com/pulp-platform/ara/issues/67
- When cloning DTC from main makefile, use HTTPS, the official git protocol
- Use HTTPS for newlib-cygwin in .gitmodules
> Move to HTTPS protocol for git repos (DTC and NEWLIB)

- CHANGELOG.md
- README.md
- hardware/Makefile
- hardware/tb/verilator/lowrisc_dv_verilator_simutil_verilator/cpp/verilated_toplevel.h
- hardware/tb/verilator/lowrisc_dv_verilator_simutil_verilator/cpp/verilator_sim_ctrl.cc
This PR adds waveform dumping capabilities to the Verilator model, through the usage of the `trace=1` option. This is based on @kuopinghsu's commit and work on the PR #62, which I changed to align it with our code style. 
Closes #60.
Closes #62.
- Makefile option (`trace=1`) to generate waveform traces when running simulations with Verilator
> Dump waveforms with Verilator

- Bender.yml
- CHANGELOG.md
- hardware/Makefile
- hardware/scripts/wave_ara.tcl
- hardware/scripts/wave_core.tcl
- hardware/scripts/wave_lane.tcl
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/tb/ara_testharness.sv
This PR creates an `ara_system`, which contains Ara, Ariane, and an AXI mux. This module is then instantiated in the `ara_soc` module. The purpose of this is to simplify our implementation scripts, which can PnR the system without worrying about the SoC logic present in `ara_soc`. 
- Create \`ara_system\` wrapper containing Ara, Ariane, and an AXI mux, instantiated from within Ara's SoC
> Create the `ara_system` wrapper

- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/valu.sv
- hardware/src/lane/vmfpu.sv
- hardware/src/masku/masku.sv
- hardware/src/sldu/sldu.sv
- hardware/src/vlsu/vldu.sv
- hardware/src/vlsu/vstu.sv
With this PR, the sequencer is changed to:
1) Alleviate the timing pressure between the lanes and the main sequencer.
2) Allow the sequencer to issue instructions to non-full units, even if other units are full.
The sequencer now implements counters to check if a specific unit is ready or not, and instructions are counted (i.e. validated) upon entrance.
**Lane synchronization**: ALU and MFPU have only one dedicated counter each in the sequencer, and the related `done` signals come from `lane 0`. This mechanism works if `lane 0` is the last at finishing the execution. For this reason, in the case of a lane de-synchronization in which `lane 0` finishes executing an instruction and there is at least another lane that is still executing the same instruction, the sequencer stalls until all the …
> Sequencer upgrade

- CHANGELOG.md
- hardware/src/lane/lane_sequencer.sv
Thank you @yanghao for your toy example that allowed us to find this bug.
The lane sequencer was calculating a wrong `vl` for the mask-unit operand requester. 
We fixed this in this PR.
- The lane sequencer now calculates the correct number of elements to be requested by the `MASKU` operand requesters.
> Hotfix - MASKU operand requesters bug

- CHANGELOG.md
- FUNCTIONALITIES.md
- apps/riscv-tests/isa/rv64uv/Makefrag
- apps/riscv-tests/isa/rv64uv/vredand.c
- apps/riscv-tests/isa/rv64uv/vredmax.c
- apps/riscv-tests/isa/rv64uv/vredmaxu.c
- apps/riscv-tests/isa/rv64uv/vredmin.c
- apps/riscv-tests/isa/rv64uv/vredminu.c
- apps/riscv-tests/isa/rv64uv/vredor.c
- apps/riscv-tests/isa/rv64uv/vredsum.c
- apps/riscv-tests/isa/rv64uv/vredxor.c
- apps/riscv-tests/isa/rv64uv/vwredsum.c
- apps/riscv-tests/isa/rv64uv/vwredsumu.c
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/operand_queue.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/lane/operand_requester.sv
- hardware/src/lane/simd_alu.sv
- hardware/src/lane/valu.sv
- hardware/src/lane/vector_fus_stage.sv
- hardware/src/sldu/sldu.sv
- hardware/src/vlsu/addrgen.sv
Add single-width and widening integer reductions to Ara, and solve some related bugs.
- When the instruction queue of the SLDU is not empty, read from it to update the commit counter, and not from the incoming request
- If an instruction targets more FUs, all of them must be ready to let the instruction be dispatched by the sequencer
- Vector integer reductions (`vredsum`, `vredmaxu`, `vredmax`, `vredminu`, `vredmin`, `vredand`, `vredor`, `vredxor`, `vwredsumu`, `vwredsum`)
> Integer Reductions

- CHANGELOG.md
- hardware/src/ara.sv
- hardware/src/ara_sequencer.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/operand_requester.sv
- hardware/src/masku/masku.sv
- hardware/src/sldu/sldu.sv
- hardware/src/vlsu/vldu.sv
- hardware/src/vlsu/vlsu.sv
1) When the main sequencer dispatches an instruction in cycle C, it calculates the hazard bits for that instruction without checking if the offending instruction was already over or not. In the same cycle, the main sequencer assigns the ID to the dispatched instruction.
This means that instruction `B` (unknown ID) can depend upon instruction `A` (ID 1), and instruction `A` can finish before `B` is dispatched. When `B` is dispatched, it can take the same ID of instruction `A`. If this is the case (instruction `B` with ID 1), we will deadlock downstream. 
This is because the hazards bits were calculated without taking into consideration that `A` was already over. Since hazards bits are cleared ID-wise, instruction `B` will now have a hazard on ID 1, but ID 1 is instruction `B` itself! This …
> Hotfix - Main Sequencer

- CHANGELOG.md
- hardware/src/lane/lane_sequencer.sv
- hardware/src/masku/masku.sv
Hotfixes for the MASKU.
A note on the commit "[hardware] bug MASKU does not wait for valid B data from inactive lanes": the valid from the inactive lanes is artificially created in the MASKU.
- MASKU does not wait anymore for valid incoming data from inactive lanes
- Fix corner-case comparison in MASKU to provide the expected behavior
- Fix MaskB-queue vector length in the lane sequencer
> MASKU hotfixes

- CHANGELOG.md
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/valu.sv
A bunch of fixes for the reduction engine and how the MASKU operations run on the VALU/VMFPU.
- VALU cleans up the partial result of a reduction when no more needed
- VALU can step from normalOp->reduction and vice-versa without issues
- VALU's counters can now count bits when operating on mask vectors
- Fix the vector length for mask instructions that run on the VALU/VMFPU
> Hotfixes for int Reductions and MASKU

- CHANGELOG.md
- hardware/src/sldu/sldu.sv
Hotfix for the SLDU. Don't let the SLDU run during an indexed memory operation.
- Don't let indexed memory operations interfere with the reductions in MASKU
> Fix interference between idx mem ops and reductions

- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/lane/vmfpu.sv
`fpnew` is composed of different unbalanced pipelined datapaths,
therefore it's possible that new instructions finish execution
before older ones.
In Ara, this should never happen. Therefore, if a potential latency
problem is detected, the issue instruction stalls.
Closes #33.
- Enforce strict in-order execution of FPU operations in VMFPU
> VMFPU in-order execution

- CHANGELOG.md
- hardware/src/axi_inval_filter.sv
Fix invalidation policy upon vector stores to misaligned addresses (misaligned wrt the D$ line width).
The previous HW was simpler but wrong. We introduced a simple adder (with 512 bit of cache line width, the adder is a 7-bit one) to quantify the misalignment w.r.t. the cache line.
- Fixed AXI-inval-filter policy for D$ lines invalidation upon vector stores that are misaligned w.r.t. the D$ line width
> Fix D$ lines invalidation policy

- CHANGELOG.md
- hardware/src/lane/lane_sequencer.sv
FP-comparisons are handled by the in-lane FPUs, and then are sent to the Mask Unit for commit. The `vfu` is officially the MaskUnit, but the operands are fetched by the FPU operand requesters. Thus, the FPU operand requesters should be ready to accept the new request.
- Fix lane sequencer checks for floating-point comparisons
> Fix lane sequencer checks for FP-comparisons

- CHANGELOG.md
- hardware/src/masku/masku.sv
Continuous assignment in the always block of mask unit is non-synthesizable. Fixed the issue by removing assign statement from the always block 
- Synthesis error  
- NA
- Removed the assign statement from the procedural block in the masku.sv
> Removed the continuous assignment from the always block of mask unit

- CHANGELOG.md
- Makefile
- apps/common/runtime.mk
- apps/fconv2d/fconv2d.h
- apps/fconv3d/fconv3d.h
- apps/jacobi2d/main.c
- apps/riscv-tests/isa/Makefile
- apps/riscv-tests/isa/rv64uv/vmerge.c
- apps/riscv-tests/isa/rv64uv/vmv.c
Update LLVM to version `15.0.0` and Spike to `1.1.1-dev`.
This updates the RVV support to 1.0 frozen.
- Fix wrong variable in `vmerge` and `vmv` `riscv-tests`
- Update LLVM to version `15.0.0` (RVV 1.0)
- Update Spike to version `1.1.1-dev` (RVV 1.0)
- Update `newlib` from commit `84d068` to `5192d5`
> Update newlib and LLVM/Spike to RVV1.0

- CHANGELOG.md
- FUNCTIONALITIES.md
- apps/riscv-tests/isa/macros/vector/vector_macros.h
- apps/riscv-tests/isa/rv64uv/Makefrag
- apps/riscv-tests/isa/rv64uv/vfmvfs.c
- apps/riscv-tests/isa/rv64uv/vfmvsf.c
- apps/riscv-tests/isa/rv64uv/vmvsx.c
- apps/riscv-tests/isa/rv64uv/vmvxs.c
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/lane/operand_requester.sv
- hardware/src/lane/simd_alu.sv
Add support for Integer/Floating-Point scalar move instructions + related tests.
- Operand requesters should fetch at least one operand after rescaling
- Integer and Floating-Point scalar move instructions (`vmv.x.s`, `vmv.s.x`, `vmv.f.s`, `vmv.s.f`)
> Add support for scalar moves

- CHANGELOG.md
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
The last PR introduced two bugs. The CI had problems this week, and the bugs remained unnoticed. 
They are solved with this PR.
- Re-introduce `WAIT_STATE` to avoid hazards when changing `LMUL`
- Fix the PEs-ready signals related conditions in the main sequencer
- Ara's dispatcher goes to `WAIT_STATE` only when the new `LMUL` is lower than the old one
> Hotfixes for main branch

- CHANGELOG.md
- hardware/src/vlsu/addrgen.sv
Hotfix for `addrgen.sv`.
The `aligned_end_addr` signal should consider the misalignment by adding `AxiDataWidth/8` only at the very last burst.
- Fix misaligned memory operations with more than 255 beats (>= 256 beats)
> Hotfix for misaligned memory ops with more than 255 beats

- CHANGELOG.md
- hardware/src/ara_dispatcher.sv
Hardware should compare the full length of the input avl wrt MAXVL. 
Do not deploy a 64-bit comparator for this, use OR gates for upper bits since quantities are unsigned.
- Fix stripmining condition in dispatcher
> [hardware] :bug: Fix Stripmining Condition in Dispatcher

- CHANGELOG.md
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/masku/masku.sv
- hardware/src/sldu/sldu.sv
- hardware/src/vlsu/addrgen.sv
Round of hotfixes for bugs noticed while implementing new kernels.
- Fix masked `VSLIDEUP`. Use only the mask bits with index higher than the stride.
- Fix `SLDU` `issue_counter` modification upon new `VSLIDEUP` incoming instruction.
- Fix whole-register-move destination re-encoding.
- Increase addrgen queue depth to four, to better hide the memory latency.
> Generic hotfixes

- CHANGELOG.md
- README.md
- apps/Makefile
- apps/common/runtime.h
- apps/common/runtime.mk
- apps/dropout/main.c
- apps/fconv2d/main.c
- apps/fconv3d/main.c
- apps/fmatmul/main.c
- apps/hello_world/main.c
- apps/iconv2d/main.c
- apps/imatmul/main.c
- apps/jacobi2d/main.c
It is now possible to simulate the benchmarks in the `apps` folder using `spike`.
To compile `${program}` against the `spike` environment:
`cd apps`
`make bin/${program}.spike`
To run `${program}` on `spike`:
`cd apps`
`make spike-run-${program}`
For convenience, you can also just `spike-run-${program}` the target. It will be automatically compiled before execution.
If you want to copy-paste the previous commands, the variable `program` should be first initialized with the name of the program to run, e.g., `program=hello_world`.
- Add support for `apps` simulation with `spike`
> [SW] Add support for SPIKE simulations of the apps programs

- CHANGELOG.md
- hardware/src/lane/valu.sv
The previous mechanism to handle the commit during a reduction was confusing and led to bugs. 
Now, the reduction triggers its commit only after the inter-lanes phase is over.
Also, some recurrent lines of code have been grouped into macros
- INT Reductions trigger their commit only after finishing the inter-lanes phase.
> [HW] :bug: Fix reductions + Rework the VALU

- hardware/src/lane/vmfpu.sv
Fix for an erroneous rebase of the last PR.
- Fix orphan assignment of a signal that caused a latch and a driving conflict
> [hardware] :bug: Fix orphan assignment

- CHANGELOG.md
- apps/riscv-tests/isa/rv64uv/vadd.c
- hardware/include/ara_pkg.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/operand_queue.sv
Currently, the `eew` signals are not fully consistent within the design, and lead to several bugs.
With this PR, we will define strict rules to implement correctly VRF Byte encoding, Undisturbed Policy, and Reading from registers with a `EEW` (and encoding!) different from `VSEW`. 
In the case of an operation executed within the lanes (e.g., `vadd`), the lanes cannot read the vector correctly if the `vsew` of the source register is different from the `eew_q` of that register (different byte layout!). So, we need to reshuffle in this case as well. Since this is costly, the suggested software procedure is to avoid filling a register with a specific encoding and using it with a different one.
- Add simple test for reshuffle operation when `vsew != eew_vs`
- Reshuffle the source registers …
> [HW] :bug: Reshuffle the source registers when VSEW != EEW_Q

- .github/workflows/ci.yml
- Bender.yml
- CHANGELOG.md
- Makefile
- README.md
- apps/Makefile
- apps/benchmarks/benchmark/fconv2d.bmark
- apps/benchmarks/benchmark/fconv3d.bmark
- apps/benchmarks/benchmark/fmatmul.bmark
- apps/benchmarks/benchmark/iconv2d.bmark
- apps/benchmarks/benchmark/imatmul.bmark
- apps/benchmarks/main.c
- apps/common/runtime.mk
- apps/ideal_dispatcher/scripts/dump_vtrace.py
- apps/ideal_dispatcher/scripts/filter_vtrace.sh
- apps/ideal_dispatcher/scripts/vtrace.sh
- hardware/Makefile
- hardware/scripts/run_ideal.tcl
- hardware/scripts/wave_ara_ideal.tcl
- hardware/scripts/wave_ideal.tcl
- hardware/scripts/wave_lane_ideal.tcl
- hardware/src/accel_dispatcher_ideal.sv
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- patches/0003-riscv-isa-sim-patch
- scripts/benchmark.gnuplot
- scripts/benchmark.sh
- scripts/performance.py
The system can now be simulated in two different modes:
1) **Normal decoupled system** with CVA6, Ara, and Memory.
2) **Ideal-Dispatcher system** with an Ideal Dispatcher, Ara, and Memory.
The Ideal Dispatcher is just a FIFO that contains the whole dynamic vector code trace of a particular program, and can dispatch one vector instruction per cycle to Ara.
This simulation mode is useful to remove the scalar core from the final performance equation, highlighting the limitations only due to Ara.
Currently, this mode has some limitations:
- It can only be run using QuestaSim.
- We do not check that the results are correct.
The `scripts/benchmark.sh` script now benchmarks both the modes by default, and uses an external `performance.py` script to extract the performance metrics. To do so, …
> [SW, HW] Add support for ideal-dispatcher simulation

- CHANGELOG.md
- apps/fconv2d/fconv2d.h
- apps/fconv2d/fconv2d_3x3.c
- apps/fconv2d/fconv2d_7x7.c
- apps/iconv2d/iconv2d.h
- apps/iconv2d/iconv2d_7x7.c
- config/16_lanes.mk
- config/2_lanes.mk
- config/8_lanes.mk
The default configuration files have a constant `VLEN`. This means that, the more the lanes, the less the buffering capability of each lane. 
Now, the default is to keep this capability constant.
Note: if the application vector length byte size is always lower than a `size_threshold`, increasing the `VLEN` above this threshold is useless.
- 7x7 kernel `2dconv`s now support arbitrary vector lengths
- Default con `vlen` in the config files is now `NR_LANES*1024`
> Keep the ratio `VRF_SIZE`/`NR_LANES` constant.

- .github/workflows/ci.yml
- CHANGELOG.md
- apps/benchmarks/benchmark/exp.bmark
- apps/benchmarks/kernel/exp.c
- apps/benchmarks/kernel/exp.h
- apps/benchmarks/main.c
- apps/common/default_args.mk
- apps/common/rivec/LICENSE
- apps/common/rivec/vector_defines.h
- apps/cos/LICENSE
- apps/cos/kernel/cos.c
- apps/cos/kernel/cos.h
- apps/cos/main.c
- apps/cos/script/gen_data.py
- apps/exp/LICENSE
- apps/exp/kernel/exp.c
- apps/exp/kernel/exp.h
- apps/exp/main.c
- apps/exp/script/gen_data.py
- apps/ideal_dispatcher/scripts/dump_vtrace.py
- apps/log/LICENSE
- apps/log/kernel/log.c
- apps/log/kernel/log.h
- apps/log/main.c
- apps/log/script/gen_data.py
- hardware/src/accel_dispatcher_ideal.sv
- scripts/benchmark.gnuplot
- scripts/benchmark.sh
- scripts/performance.py
Implement floating-point exp-cos-log from the `RiVEC Benchmark Suite`: 
[RALC](https://github.com/RALC88/riscv-vectorized-benchmark-suite/tree/rvv-1.0) 
- Add fp-exp, fp-cos, fp-log benchmarks from `RiVEC Benchmark Suite` and print performance
- Ideal Dispatcher tracer now supports strided memory operations
- `benchmark.sh` can now also benchmark just one app at a time via an input argument
> [SW] New Benchmarks: `exp-cos-log` (+plot performance)

- CHANGELOG.md
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/valu.sv
Various fixes:
- Fix lmul checks on `vs1` for conversion instructions
- Fix `eew_vs1` for widening instructions
- Fix cleaning of the accumulator after partial reduction in `valu`
> [HW] Misc fixes for Dispatcher and VALU

- apps/riscv-tests/isa/macros/vector/vector_macros.h
- apps/riscv-tests/isa/rv64uv/Makefrag
- apps/riscv-tests/isa/rv64uv/vsetivli.c
- apps/riscv-tests/isa/rv64uv/vsetvl.c
- apps/riscv-tests/isa/rv64uv/vsetvli.c
Updated vector configuration setting instructions tests and vector macros.
- Updated vector configuration setting instructions tests for different combinations of SEW and LMUL
- Updated vector macro `check_vtype_vl` to check for illegal combinations of SEW and LMUL
- Updated `Makefrag` file to add `vsetvli` and `vsetvl` tests
- None
- None
- Added test cases for different combinations of SEW and LMUL in vector configuration setting instructions tests
- Added a check for illegal combinations of SEW and LMUL in `check_vtype_vl` macro in `vector_macros.h` file
- Added tests of `vsetvli` and `vsetvl` in Makefrag file
> Updated configuration setting tests and vector macros

- CHANGELOG.md
- README.md
- hardware/src/vlsu/addrgen.sv
Currently, the `addrgen` calculates the next aligned start address by adding +1 to the current aligned end address. 
This is redundant since, when calculating the next aligned end address, we also implicitly calculate the next start address, which can be buffered for the next cycle avoiding the expensive addition on 64 address bits.
Unluckily, the 4 KiB page checks require some additional operations. 
- Buffer the next aligned start address in the `addrgen`, avoiding redundant addition on a possibly critical path.
> [HW] Cut problematic adder path in addrgen

- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/operand_queue.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/lane/operand_requester.sv
- hardware/src/lane/vmfpu.sv
- hardware/src/sldu/sldu.sv
- hardware/src/vlsu/addrgen.sv
Various hotfixes, especially around the FPU reductions.
- New reductions should start only when previous operation is over
- Prevent VMFPU from ack the opqueues when their issue is over
- Operand requesters sanitize the partial operands
- Fix load/store-complete signals to CVA6
> [HW] Hotfix to run roi-align and lavaMD correctly

- CHANGELOG.md
- FUNCTIONALITIES.md
- apps/riscv-tests/isa/rv64uv/Makefrag
- apps/riscv-tests/isa/rv64uv/vcpop.c
- apps/riscv-tests/isa/rv64uv/vfirst.c
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/simd_alu.sv
- hardware/src/masku/masku.sv
Added support for vector population count `vcpop` and vector find first set bit `vfirst` instructions
- N/A
- Support for vector population count `vcpop` and vector find first set bit `vfirst` instructions
- Test for  vector population count `vcpop` instruction
- Test for find first set bit `vfirst` instruction
> [HW] Add support for vcpop and vfirst instructions

- Bender.yml
- CHANGELOG.md
- FUNCTIONALITIES.md
- apps/riscv-tests/isa/macros/vector/vector_macros.h
- apps/riscv-tests/isa/rv64uv/Makefrag
- apps/riscv-tests/isa/rv64uv/vaadd.c
- apps/riscv-tests/isa/rv64uv/vaaddu.c
- apps/riscv-tests/isa/rv64uv/vnclip.c
- apps/riscv-tests/isa/rv64uv/vnclipu.c
- apps/riscv-tests/isa/rv64uv/vsadd.c
- apps/riscv-tests/isa/rv64uv/vsaddu.c
- apps/riscv-tests/isa/rv64uv/vsmul.c
- apps/riscv-tests/isa/rv64uv/vssra.c
- apps/riscv-tests/isa/rv64uv/vssrl.c
- apps/riscv-tests/isa/rv64uv/vssub.c
- apps/riscv-tests/isa/rv64uv/vssubu.c
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/src/lane/fixed_p_rounding.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/simd_alu.sv
- hardware/src/lane/simd_mul.sv
- hardware/src/lane/valu.sv
- hardware/src/lane/vector_fus_stage.sv
- hardware/src/lane/vmfpu.sv
- hardware/tb/ara_tb.sv
Add support for `vssra`, `vssrl`, `vnclip`, `vnclipu` and `vsmul` vector fixed-point instructions
- N/A
- Support for vector single-width fractional multiply with rounding and saturation instruction: `vsmul`
- Support for vector single-width scaling shift instructions: `vssra`, `vssrl`
- Support for vector narrowing fixed-point clip instructions: `vnclip`, `vnclipu`
- Test for `vnclip` and `vnclipu` vector fixed-point instructions
- Updated tests for `vssra`, `vssrl` and `vsmul` vector fixed-point instructions
> [HW] Add support for vector fixed-point instructions

- CHANGELOG.md
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/lane_sequencer.sv
Handle reshuffles when LMUL > 1. Before, only the first register was reshuffled. Now, every register belonging to the register group is checked and, if needed, reshuffled.
- Reshuffle all the registers of a register group that have `eew_q != eew_d` when `LMUL > 1`.
- Wait for `SlideAddrGenA` operand requester during a `VLXE` or `VSXE`.
> [HW] :bug: Hotfix - Reshuffle with LMUL > 1

- CHANGELOG.md
- README.md
- apps/common/arch.link.ld
- apps/common/runtime.h
- apps/common/runtime.mk
- apps/common/util.h
- apps/cos/kernel/cos.c
- apps/dropout/kernel/dropout.c
- apps/dwt/kernel/wavelet.c
- apps/exp/kernel/exp.c
- apps/fconv3d/fconv3d_3x7x7.c
- apps/fft/kernel/fft.c
- apps/fft/main.c
- apps/fmatmul/kernel/fmatmul.c
- apps/fmatmul/kernel/fmatmul.h
- apps/fmatmul/main.c
- apps/jacobi2d/kernel/jacobi2d.c
- apps/jacobi2d/kernel/jacobi2d.h
- apps/jacobi2d/main.c
- apps/log/kernel/log.c
- hardware/Makefile
- hardware/src/ara_soc.sv
- hardware/src/ctrl_registers.sv
- hardware/src/lane/vmfpu.sv
- hardware/tb/ara_tb.sv
- hardware/tb/ara_testharness.sv
SW: Add initial support for power analysis with automatic VCD dumping for the following kernels: `fmatmul`, `fconv3d`, `fft`, `dwt`, `exp`, `cos`, `log`, `dropout`, `jacobi2d`.
HW: power gate the in-lane SIMD multipliers.
- Add HW/SW environment for automatic VCD dumping.
- Generate data for `fmatmul` at compile time.
- SIMD multipliers are now power gated.
> [HW, SW] Add Power Analysis feature

- CHANGELOG.md
- FUNCTIONALITIES.md
- apps/riscv-tests/isa/rv64uv/Makefrag
- apps/riscv-tests/isa/rv64uv/vfrec7.c
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/simd_alu.sv
- hardware/src/lane/simd_mul.sv
- hardware/src/lane/valu.sv
- hardware/src/lane/vector_fus_stage.sv
- hardware/src/lane/vmfpu.sv
vfrec7 is a unary vector-vector instruction that returns an estimate of 1/x accurate to 7 bit.
- Exceptional cases are according to table.
- For the non-exceptional cases:
- If the input is normal, normalized input exponent is equal to the input exponent and normalized input significand(mantissa) is equal to the input significand.
- If the input is subnormal, normalized input exponent is equal to 0 minus the number of leading zeros in the signifcand and the normalized input significand is given by shifting the input significand left by 1 minus the normalized input exponent.
- For normalization only two MSBs bits of significand are considered for counting the number of leading zeros, all other bits are ignored according to table.
- If the significand=01..., the number of leading zeros is …
> [HW] Add support for vfrec7 instruction

- CHANGELOG.md
- Makefile
Verilator v4.226 raises unexpected errors at runtime.
- Roll-back to Verilator v4.214
> [SW] Roll-back to Verilator v4.214

- CHANGELOG.md
- FUNCTIONALITIES.md
- apps/riscv-tests/isa/rv64uv/Makefrag
- apps/riscv-tests/isa/rv64uv/vfrsqrt7.c
- hardware/include/ara_pkg.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/vmfpu.sv
vfrsqrt7 is a unary vector-vector instruction that returns an estimate of 1/sqrt(x) accurate to 7 bit.
For the non-exceptional cases:
- If input is normal, normalized input exponent is equal to the input exponent and normalized input significand(mantissa) is equal to the input significand.
- If input is subnormal, normalized input exponent is equal to 0 minus the number of leading zeros in the signifcand and the normalized input significand is given by shifting the input significand left by 1 minus the normalized input exponent.
- Output exponent can be found by:
exp_o = (3*B-1-exp_i )/2
where B is exponent bias.
- Output 7-bit significand can be found by using lookup table.
- The address of lookup table is found by concatenating last LSB of the normalized input exponent and the six MSBs …
> [HW] Add support for vfrsqrt7 instruction

- .github/workflows/sphinx.yml
This PR fixes the issues of rendering Html pages of documentation from the main branch. After the merge of PR #199, the documentation pages will render from the main. sphinx.yml file build and deploy the Html files automatically (on push) on the gh-pages branch. GitHub page settings are shown below. 
After these changes and merge of this PR, the expected docs URL will be https://pulp-platform.github.io/ara/
- Updates sphinx.yml file.
> [CI] Update sphinx.yml to publish GitHub-pages from main branch

- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/lane/operand_queue.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/vlsu/addrgen.sv
Opqueues should have two different depths, one for the control (how many instructions can be buffered), and one for the data (how many 64-bit packets can be buffered).
- Decouple `cmdBuffer` and `dataBuffer` depths in opQueues
- Parametrize `addrgen` queue depth
> [HW] Hotfix for Opqueue buffer depths

- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/vmfpu.sv
- hardware/src/masku/masku.sv
1) VMFPU has more than one units, and as soon as the issue phase of an instruction is over, the next one can start. If instruction 1 is a `div` instruction and takes 6 cycles, while instruction 2 is a 8 bit multiplication and takes 1 cycles only, the results can be produced out-of-order. For this reason, the units are handshaked at their output only if the unit is used by `vinsn_processing_q`.
2) The mask unit handles logical mask operations if `vs1`, `vs2`, and `vd` have the same `eew` encoding. Therefore, these operations should be affected by reshuffling. EW8 is preferred for all the mask operations to minimize reshuffling.
3) `vmv.v.v` and `vmerge` need to be affected by reshuffling. To speed up everything, `vmv.v.v` align the working encodings to the `eew` of the source register, to …
> [HW] :bug: Hotfix to reshuffling engine and FPU

- Bender.yml
- CHANGELOG.md
- apps/imatmul/kernel/imatmul.c
- apps/imatmul/kernel/imatmul.h
- apps/imatmul/main.c
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/src/lane/power_gating_generic.sv
- hardware/src/lane/vmfpu.sv
- hardware/tb/ara_tb.sv
- hardware/tb/ara_testharness.sv
- Add guards in the testbench to successfully compile in post-layout simulations.
- Add VCD dumping features to `imatmul`.
- `core_id_i` added to the interface of the system.
- SIMD-multipliers are now gated singularly depending on VSEW.
> [HW] Generic hotfixes (post-layout simulation)

- CHANGELOG.md
- hardware/src/lane/vector_regfile.sv
Clock gate the bank memory macros when not used. This allows for critical power saving.
- Clock gate the VRF, D$, I$ banks when not used.
> [hardware] Clock-Gate VRF and Scalar Cache banks

- CHANGELOG.md
- hardware/src/lane/vmfpu.sv
The registers that clock gate the SIMD multipliers were not reset.
- Reset the gating registers before the int multipliers.
> [HW] Fix multiplier gating registers X injection

- .gitmodules
- Bender.lock
- Bender.yml
- hardware/src/ara_soc.sv
axi2apb_64_32 has been deprecated. Replace it with the up-to-date axi and apb IPs.
> ara_soc: Upgrade axi to apb

- CHANGELOG.md
- hardware/src/lane/valu.sv
Hello,
as #163 mentions the `vnclip` and `vnclipu` are not working properly. I also observed this problem when testing this instruction. 5979a98570ad6122e07c8c5f1705b5003df1b0b0 fixes this problem by adding `vnclip` and `vnclipu` to the `narrowing( ... )` function.
- Fix narrowing for `vnclip` and `vnclipu`
> Fix vnclip vnclipu

- CHANGELOG.md
- hardware/src/ara_dispatcher.sv
The floating-point scalar moves did not NaN-box the scalar forwarded back to CVA6 for 32- and 16-bit values.
Now they do.
- Fix scalar-NaN boxing for floating-point scalar moves.
> [hardware] NaN-box the scalar value before forwarding back to CVA6

- .github/workflows/ci.yml
- CHANGELOG.md
- apps/Makefile
- apps/benchmarks/benchmark/dotproduct.bmark
- apps/benchmarks/benchmark/fconv3d.bmark
- apps/benchmarks/benchmark/fdotproduct.bmark
- apps/benchmarks/benchmark/fmatmul.bmark
- apps/benchmarks/benchmark/jacobi2d.bmark
- apps/benchmarks/benchmark/roi_align.bmark
- apps/common/default_args.mk
- apps/common/runtime.mk
- apps/dotproduct/script/gen_data.py
- apps/dwt/kernel/wavelet.c
- apps/fconv3d/fconv3d.h
- apps/fconv3d/fconv3d_3x7x7.c
- apps/fdotproduct/script/gen_data.py
- apps/fft/main.c
- apps/ideal_dispatcher/scripts/dump_vtrace.py
- apps/jacobi2d/kernel/jacobi2d.c
- apps/roi_align/kernel/roi_align.c
- apps/roi_align/kernel/roi_align.h
- apps/roi_align/main.c
- hardware/src/accel_dispatcher_ideal.sv
- hardware/tb/ara_tb.sv
- hardware/tb/ara_testharness.sv
- scripts/benchmark.sh
- scripts/check_cycles.py
- scripts/format_summary.py
- scripts/performance.py
- scripts/plot2d.py
Improve performance measurement scripts and kernels.
- Fix dump vtrace script for vsetvli instructions without x0 (ideal dispatcher)
- Fix Pathfinder and FFT performance
- Plot kernels-Vl performance plot
- Print I$/D$ stall metrics
- Optimize Jacobi2d
- Benchmark only the vector kernel in roi_align
- Improve cache warming functions
- [f]dotproduct works on the vector length in elements
- Optimize DWT
- Fix pathfinder performance
> [SW] Fix kernel performance calculation

- hardware/Makefile
With the new `common_cells`, a guard macro has been introduced to keep out assertions during simulations, as they are not 100% compatible with all the simulation tool versions (e.g., Verilator).
We therefore disable them.
- Disable `common_cells` assertions in verilator.
> [hardware] disable common-cells assertions forr verilator

- .github/workflows/ci.yml
- Bender.local
- Bender.lock
- Bender.yml
- CHANGELOG.md
- README.md
- hardware/Makefile
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/src/lane/vmfpu.sv
- hardware/tb/dpi/elfloader.cc
Bump CVA6 to a recent version from OpenHW Group.
Moreover, use `Bender.lock` and remove `Bender.local` to improve reproducibility.
- Disable common_cells assertions when simulating with Verilator
- Bender checkout instead of update
- Remove Bender.local (use Bender.lock for reproducibility)
- Update CVA6 to OpenHW group master branch
> [HW] Bump CVA6 to `pulp-v1`

- Bender.lock
- Bender.yml
- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/vlsu/addrgen.sv
- hardware/src/vlsu/vlsu.sv
https://github.com/pulp-platform/ara/pull/270 rework
This PR aims to introducing:
Various bug fixes (including exception generation and handling + reshuffle mechanism) .
Basic support for RVV CSR vstart.
- Stall Ara and wait for ara_idle upon CSR write/read
- Fix how VLSU reports exceptions
- Set vstart=0 upon succesfull vector instructions
- Fix vstart usage in ara dispatcher
- Fix reshuffle mechanism
- Rename CSRs in dispatcher to improve clarity
- Change from reporting "errors" to full "exceptions"
- Bump CVA6 to version that supports "exceptions" reporting
> [HW] 🐛 Bug fixes

- CHANGELOG.md
- hardware/Makefile
- hardware/include/ara_pkg.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/operand_queue.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/lane/operand_requester.sv
- hardware/src/lane/valu.sv
- hardware/src/lane/vector_fus_stage.sv
- hardware/src/lane/vmfpu.sv
- hardware/src/masku/masku.sv
- hardware/src/sldu/sldu.sv
- hardware/src/vlsu/addrgen.sv
- hardware/src/vlsu/vldu.sv
- hardware/src/vlsu/vlsu.sv
- hardware/src/vlsu/vstu.sv
- hardware/tb/ara_tb.sv
- hardware/tb/ara_tb_verilator.sv
- hardware/tb/ara_testharness.sv
- hardware/tb/verilator/waiver.vlt
`VLEN` is now a parameter of the Ara module. 
The `ara_package.sv` code does not depend on defines anymore.
- `VLEN` is now a parameter of the ara architecture and does not depend on a define anymore
- `vlen_t`, as a consequence, is now define within the architecture as a parameter/localparam
- Change verilation from hierarchical (lane -> Ara) to fully flat (Ara)
> [HW] Make `VLEN` a module parameter

- hardware/src/vlsu/addrgen.sv
This wrong type caused a lot of warnings when simulating with Cheshire + Ara.
> [hardware] Fix type of i_addrgen_idx_op_spill_reg

- CHANGELOG.md
- hardware/src/ara_soc.sv
Fix nasty bug in printf.
- Fix printf bug - UART and CTRL regions are now idempotent
- Memory size is now fixed regardless of `NrLanes`
> [HW] :bug: Fix printf missing characters bug

- CHANGELOG.md
- hardware/src/lane/valu.sv
If the result queue is not empty and we start a reduction, the state of the ALU goes to INTRA_LANE_REDUCTION. Here, the VRF write-back of the previous instruction does not happen. Moreover, the INTRA_LANE_REDUCTION needs the result queue for its own purposes.
- Start integer reductions only if the result queue is empty
> [hardware] Fix hanging integer reductions

- Bender.lock
- Bender.yml
- CHANGELOG.md
Bump CVA6 to fix bug that caused some vector instructions to be issued twice in the presence of instructions with side effects.
- Fix `fence` bug in CVA6.
> [HW] Fix CVA6 bug for instructions with side effects

- CHANGELOG.md
- hardware/Makefile
- hardware/include/ara/ara.svh
- hardware/include/ara/ara_typedef.svh
- hardware/src/ara.sv
- hardware/src/lane/lane.sv
- hardware/tb/verilator/waiver.vlt
Finally, Verilator [will support](https://github.com/verilator/verilator/pull/5333) custom parameters through hierarchical blocks. Waiting for the next stable release, this is a temporary fix not to crash the 16-lane verilation on GitHub CI servers.
The hierarchical compilation feature was once removed because of a custom parameter type being passed by Ara to the Lane modules. Verilator did not like this, so we removed hierarchical verilation. However, the github CI cannot compile the 16-lane design anymore without running out of memory.
Description of PR that completes issue here...
- Add hierarchical Verilation
> [HW] Add hierarchical Verilation 

- Bender.lock
- CHANGELOG.md
Solve verilation warnings (missing pins).
- Bump common_cells and axi to solve verilation warnings
> [Bender] Bump common_cells and axi to solve verilation warnings

- CHANGELOG.md
- hardware/include/ara_pkg.sv
- hardware/src/lane/operand_queue.sv
- hardware/src/lane/vmfpu.sv
Following up: https://github.com/pulp-platform/ara/pull/222
- Fix NaN handling during opqueue floating-point coversions
- Fix subnormal handling during optuque floating-point conversions
> [HW] 🐛 Fix for floating-point NaN/subnormal handling in opqueues

- hardware/src/lane/valu.sv
Fix a race condition in `vredsum`.
- Fix `vredsum` race condition in VALU.
> [hardware] :bug: Fix alu reduction race condition

- apps/common/crt0.S
Removed a redundant `li x10, 0` instruction in the reset_vector section of crt0.S. This cleanup improves code clarity without altering the functionality.
> [SW] Remove redundant instruction in reset_vector

- hardware/src/lane/simd_alu.sv
This PR addresses a bug in the simd_alu module that caused incorrect results for the vasub and vasubu instructions. The issue was identified and corrected, ensuring the instructions now produce accurate results.
- Fix vasub&vasubu error in simd_alu.
- Simulated apps/riscv-tests/isa/rv64uv/vasub PASS using verilator and vcs.
> [hardware] 🐛Fix vasub&vasubu error in simd_alu.

- Bender.lock
- Bender.yml
- CHANGELOG.md
- apps/riscv-tests/isa/rv64uv/vmand.c
- apps/riscv-tests/isa/rv64uv/vmandnot.c
- apps/riscv-tests/isa/rv64uv/vmnand.c
- apps/riscv-tests/isa/rv64uv/vmnor.c
- apps/riscv-tests/isa/rv64uv/vmor.c
- apps/riscv-tests/isa/rv64uv/vmornot.c
- apps/riscv-tests/isa/rv64uv/vmxnor.c
- apps/riscv-tests/isa/rv64uv/vmxor.c
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/operand_requester.sv
- hardware/src/masku/masku.sv
- hardware/src/masku/masku_operands.sv
- hardware/src/vlsu/addrgen.sv
- hardware/src/vlsu/vldu.sv
- hardware/src/vlsu/vstu.sv
A series of fixes and modifications to ease timing closure.
- Bump upload and delete artifact actions
- Fix synthesis-unfriendly constructs
- Cut CVA6 - Ara combinatorial path on instruction interface
- Parametrize OS support (disabled by default)
- Cut ready-path between VLSU and MASKU
- Relax tight ADDRGEN timing path
- Time multiplex VCPOP and VFIRST ops in MASKU
- Refactor MASKU
- Remove bit-support for tail elements
- Adapt mask tests to this behavior
- Use only one commit port in CVA6
> [HW] A series of fixes to improve timing

- CHANGELOG.md
- FUNCTIONALITIES.md
- apps/riscv-tests/isa/rv64uv/Makefrag
- apps/riscv-tests/isa/rv64uv/vlff.c
- hardware/include/ara/ara_typedef.svh
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/vlsu/addrgen.sv
- hardware/src/vlsu/vlsu.sv
[hardware] Add support for `fault-only-first` loads.
- Add support for fault-only-first loads
> [hardware] Add `fault-only-first` loads

- CHANGELOG.md
- hardware/src/vlsu/addrgen.sv
- hardware/src/vlsu/vldu.sv
Optimize `addrgen` stage for better timing.
- Pre-calculate some critical addresses to ease timing
> [HW] Optimize timing-critical address calculation

- .github/workflows/ci.yml
- CHANGELOG.md
- apps/benchmarks/benchmark/lavamd.bmark
- apps/benchmarks/kernel/lavamd.c
- apps/benchmarks/kernel/lavamd.h
- apps/benchmarks/lib/exp.h
- apps/benchmarks/main.c
- apps/common/default_args.mk
- apps/common/rivec/vector_defines.h
- apps/lavamd/LICENSE
- apps/lavamd/LICENSE_1
- apps/lavamd/kernel/lavamd.c
- apps/lavamd/kernel/lavamd.h
- apps/lavamd/lib/exp.h
- apps/lavamd/main.c
- apps/lavamd/script/gen_data.py
- hardware/src/sldu/sldu.sv
- scripts/benchmark.gnuplot
- scripts/benchmark.sh
- scripts/check_cycles.py
- scripts/performance.py
Add lavaMD benchmark from RiVEC Benchmark Suite. Performance is DUMMY (should be zero for now).
- Add `lavaMD` benchmark to `apps`, `benchmarks`, `CI`
> [SW] Add lavaMD benchmark

- CHANGELOG.md
- hardware/src/ara.sv
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/src/vlsu/addrgen.sv
Enable OS by default and optimize `addrgen` critical paths.
Most of the `addrgen` critical quantities are calculated in advance with the least dependencies possible.
For example, the expensive computation to find the AXI end address should not depend on the `mmu_valid_i` signal from CVA6, i.e., the virtual address computation should not depend on CVA6's answer. 
The new address can be computed ahead of time and saved as "next request" as soon as CVA6 answers back with the previous physical address, while the old virtual address is kept constant with the translation request.
- Optimize `addrgen` for OS-on operation
- Enable OS by default
> [HW] Optimize `addrgen` for OS-on operation

- CHANGELOG.md
- cheshire/Makefile
- cheshire/sw/Makefile
- cheshire/sw/include/rvv_test.h
- cheshire/sw/src/tests/body/rvv_test_mmu_stub_unit_stride_comprehensive.c.body
- cheshire/sw/src/tests/body/rvv_test_mmu_stub_unit_stride_ld_comprehensive.c.body
- cheshire/sw/src/tests/body/rvv_test_vstart_unit_stride.c.body
- cheshire/sw/src/tests/body/rvv_test_vstart_unit_stride_mmu_stub_page_fault.c.body
- cheshire/sw/src/tests/regfile_text_stub_regs.c
- cheshire/sw/src/tests/rvv_test_exceptions.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_comprehensive_page_fault_var_lat.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_comprehensive_page_fault_var_lat_var_ex.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_comprehensive_var_lat.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_corner_cases.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_ld_comprehensive_page_fault_var_lat.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_ld_comprehensive_page_fault_var_lat_var_ex.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_ld_comprehensive_var_lat.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_reshuffle.c
- cheshire/sw/src/tests/rvv_test_mmu_stub_unit_stride_st_reshuffle.c
- cheshire/sw/src/tests/rvv_test_vstart_csrs.c
- cheshire/sw/src/tests/rvv_test_vstart_unit_stride_mmu_stub_page_fault_var_lat.c
- cheshire/sw/src/tests/rvv_test_vstart_unit_stride_mmu_stub_page_fault_var_lat_mmu_req_gen.c
- cheshire/sw/src/tests/rvv_test_vstart_unit_stride_mmu_stub_var_lat.c
- hardware/src/ara_dispatcher.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/operand_requester.sv
- Align `g++` version with cheshire's if simulating with it (for QuestaSim).
- Don't compile the first-pass-decoder in CVA6 (need for a specific bender target).
- Solve type-conversion warnings about type conversions.
- Add RVV tests to be used with Cheshire's stub and specific debug environment.
> [HW/SW] Cheshire-related fixes

- .github/workflows/sphinx.yml
- CHANGELOG.md
- cheshire/sw/include/rvv_test.h
- cheshire/sw/include/vector_util.h
- cheshire/sw/src/tests/body/rvv_test_mmu_stub_idx_ld_comprehensive.c.body
- cheshire/sw/src/tests/rvv_test_mmu_stub_idx_ld_comprehensive_page_fault_var_lat_var_ex.c
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/lane_sequencer.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/lane/operand_requester.sv
- hardware/src/vlsu/addrgen.sv
- hardware/src/vlsu/vldu.sv
- hardware/src/vlsu/vlsu.sv
- hardware/src/vlsu/vstu.sv
Fix indexed loads with virtual memory.
- Correctly flush the backend pipeline upon indexed load exceptions.
- Make addrgen wait for index address before making an MMU request.
- Fix typos in lane sequencer.
> [HW] Fix flushing upon load-related exceptions

- CHANGELOG.md
- hardware/src/ara.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/operand_queue.sv
- hardware/src/lane/operand_queues_stage.sv
- hardware/src/lane/valu.sv
- hardware/src/lane/vector_fus_stage.sv
- hardware/src/lane/vmfpu.sv
- hardware/src/sldu/sldu.sv
- hardware/src/vlsu/addrgen.sv
- hardware/src/vlsu/vldu.sv
- hardware/src/vlsu/vlsu.sv
There are three transmitters (TXs) that can send data to two receivers (RXs).
```
TXs:
1) sldu/addrgen opqueue
2) alu
3) vmfpu
RXs:
1) SLDU
2) ADDRGEN
```
This is because the sldu/addrgen opqueue is shared and reductions pass through the SLDU. 
The previous control logic was flawed and indexed memory operations + reductions could not work together.
Now, we have changed some hypotheses: the RXs always receive a valid from the lanes only if the data is targeting them. 
We have two valid lines, one for the addrgen, and one for the sldu. This simplifies the logic in the SLDU.
In each lane, the selector logic to stream the correct valids/readies is controlled by a FIFO containing the selectors in program order, therefore serializing the requests correctly.
- Fix sldu/addrgen synchronization
> [HW] :bug: Fix synchronization between lanes and sldu/addrgen

- CHANGELOG.md
- hardware/src/lane/lane_sequencer.sv
- hardware/src/masku/masku.sv
Fix `vfirst`/`vcpop` in masku and mask-comparison EEW in lane seq.
- Fix `vfirst`/`vcpop` state initialization 
- Fix mask-comparison `eew` in lane seq.
> [HW] Fix `vfirst` and mask comparison `EEW`

- CHANGELOG.md
- hardware/src/lane/vmfpu.sv
Fix bug in ordered reductions.
- Prevent double bump of `insn_queue.commit_cnt` after an ordered reduction.
> [HW] Fix osum reduction counter bumping

- CHANGELOG.md
- hardware/src/lane/vmfpu.sv
Avoid spurious valids to the multipliers.
- Avoid spurious valids to the multipliers.
> [HW] Prevent multipliers from getting spurious valid signals

- Bender.lock
- Bender.yml
- CHANGELOG.md
- cheshire/Makefile
- cheshire/sw/include/rvv_test.h
- hardware/Makefile
- hardware/include/ara/intf_typedef.svh
- hardware/include/ara_pkg.sv
- hardware/src/accel_dispatcher_ideal.sv
- hardware/src/ara.sv
- hardware/src/ara_dispatcher.sv
- hardware/src/ara_sequencer.sv
- hardware/src/ara_soc.sv
- hardware/src/ara_system.sv
- hardware/src/cva6_accel_first_pass_decoder.sv
- hardware/src/lane/vmfpu.sv
- hardware/src/vlsu/addrgen.sv
- hardware/src/vlsu/vlsu.sv
Bump CVA6 to `pulp-v2`. 
Todos:
- Bump CVA6 to `pulp-v2`
- Re-parametrize the design with parameters from CVA6 `pulp-v2`
- Bump AXI version to a working one
> [HW] Bump CVA6 to `pulp-v2`

- .gitmodules
- CHANGELOG.md
- Makefile
- README.md
Add support for [rvv-bench](https://github.com/camel-cdr/rvv-bench) instruction benchmark.
Instructions from https://github.com/camel-cdr/rvv-bench/issues/17.
- Add support for `rvv-bench` instruction benchmark.
> [SW] Add support for `rvv-bench`

- .github/workflows/ci.yml
- .gitmodules
- CHANGELOG.md
- Makefile
- README.md
- cheshire/Makefile
- hardware/src/ara.sv
- hardware/src/lane/lane.sv
- hardware/src/lane/simd_div.sv
- hardware/src/lane/vector_fus_stage.sv
- hardware/src/lane/vmfpu.sv
This also includes https://github.com/pulp-platform/ara/pull/418 by mistake. They will be now merged together. See https://github.com/pulp-platform/ara/pull/418 for its changes w.r.t. `main`.
- Pass the `CVA6Cfg` to Ara's serial divider.
- Force re-generation of Cheshire's scritps.
- Free up space in runner to make toolchains.
- Update `buildroot` mirror with a more stable one.
- Don't download all the git submodules by default, and reserve a make command for that.
> Fix integration in Cheshire
